export interface Persona {
birth_date: string,
photos: string | string[],
title: string,
links: string | string[],
bio: string | string[],
source_records: string | string[],
alternate_names: string | string[],
remote_ids: string | string[],
entity_type: string | string[],
wikipedia: string | string[],
name: string | string[],
personal_name: string | string[],
key: string | string[],
type: string | string[],
latest_revision: string | string[],
revision: string | string[],
created: string | string[],
last_modified: string | string[],
}